### ISSUE TITLE
Broke poti

### ISSUE THREAD

**Issue by TheGreyDiamond** [sparkfun/GraphicLCD_Serial_Backpack#6]
Hi,
I have a problem. The trimpot of my LCD Backpack broke. The display is showing nothing. Is there any way I can fix that?

**Comment by nseidle** [comment]
Bummer! You could try replacing the SMD pot - it's a fairly common SMD 10k pot - part# [TC33X-103ETR-ND](https://www.digikey.com/product-detail/en/bourns-inc/TC33X-2-103E/TC33X-103ECT-ND/612911).

There might also be some ways to solder a permanent SMD resistor there but I'd recommend replacing with a trimpot. It's nearly impossible to pin down a single good contrast resistor value.

**Comment by TheGreyDiamond** [comment]
Okay, thanks!
